name: Sed test
on: push

jobs:
  test-sed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sed -i.bak "s|phpserver|dsadsasdsa|g" README.md && \
          cat README.md
