name: Action Test

on:
  push:
      
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      # (1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # (3) Mysql Datasource 설정 세팅
      - name: Set up Mysql Datasource- 
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "dir/fileName.txt"
          FILE_DATA: "file content"
